# Generated by Django 5.0.6 on 2024-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Cash In', 'Cash In'), ('Cash Out', 'Cash Out')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
